### PR TITLE
Fix IP address for containers

### PR DESCRIPTION
**Pull request by ailispaw**
Thank you for using DockerRoot.
I wrote some code to fix the IP address for containers.
I hope you like it.

### CODE REVIEW

**Comment by jverdeyen** [comment]
Hi! 
Thanks for your contribution!
Any reason why you prefer `172.17.42.0` to `172.18.0.0`?

**Comment by ailispaw** [comment]
Just follow an example at https://github.com/tonistiigi/dnsdock#setup.
And I recall that `172.17.42.1` was by default in the old docker daemons.

**Comment by ailispaw** [comment]
Please revise it as you like.

**Comment by ailispaw** [comment]
Or I can convert it to a variable, but I'm not familiar with a ruby manner.
Is this good for you? https://github.com/ailispaw/vagrant-docker/tree/dev

**Comment by ailispaw** [comment]
I misunderstood the IP address of containers in this case and my PR was wrong.
Because the IP address of the VM `172.17.8.101` is within the range of the default IP address of containers `172.17.0.1/16`, the Docker daemon uses `172.18.0.1/16` instead.

Hmmm. The Docker daemon uses `172.17.0.1/16` as well sometimes...

**Pull request closed without merging**
